create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_no integer not null,
  days jsonb not null default '[]'::jsonb,
  hip numeric,
  navel numeric,
  note text,
  coach text,
  updated_at timestamptz not null default now(),
  unique(user_id, week_no)
);

alter table public.checkins enable row level security;

drop policy if exists "own checkins select" on public.checkins;
create policy "own checkins select" on public.checkins for select using (auth.uid() = user_id);
drop policy if exists "own checkins insert" on public.checkins;
create policy "own checkins insert" on public.checkins for insert with check (auth.uid() = user_id);
drop policy if exists "own checkins update" on public.checkins;
create policy "own checkins update" on public.checkins for update using (auth.uid() = user_id);
drop policy if exists "own checkins delete" on public.checkins;
create policy "own checkins delete" on public.checkins for delete using (auth.uid() = user_id);
